// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAryRPY-L4aHOZcieE00yoT-LiyXuP37do',
    appId: '1:575762734530:web:fb3181d27dade8335e0a5b',
    messagingSenderId: '575762734530',
    projectId: 'idfy-1e72a',
    authDomain: 'idfy-1e72a.firebaseapp.com',
    databaseURL: 'https://idfy-1e72a-default-rtdb.firebaseio.com',
    storageBucket: 'idfy-1e72a.firebasestorage.app',
    measurementId: 'G-DSS5ZX04ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1j8ATYy49pzvg-XX-AdExBqFpG7VXGXw',
    appId: '1:575762734530:android:db0c940ebe2f73865e0a5b',
    messagingSenderId: '575762734530',
    projectId: 'idfy-1e72a',
    databaseURL: 'https://idfy-1e72a-default-rtdb.firebaseio.com',
    storageBucket: 'idfy-1e72a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi6fmwn-IP6LvPkdHmjTAbOVJCZP1DkJY',
    appId: '1:575762734530:ios:a890d73bd102e1015e0a5b',
    messagingSenderId: '575762734530',
    projectId: 'idfy-1e72a',
    databaseURL: 'https://idfy-1e72a-default-rtdb.firebaseio.com',
    storageBucket: 'idfy-1e72a.firebasestorage.app',
    iosBundleId: 'com.example.mobileappUserMember',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi6fmwn-IP6LvPkdHmjTAbOVJCZP1DkJY',
    appId: '1:575762734530:ios:a890d73bd102e1015e0a5b',
    messagingSenderId: '575762734530',
    projectId: 'idfy-1e72a',
    databaseURL: 'https://idfy-1e72a-default-rtdb.firebaseio.com',
    storageBucket: 'idfy-1e72a.firebasestorage.app',
    iosBundleId: 'com.example.mobileappUserMember',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAryRPY-L4aHOZcieE00yoT-LiyXuP37do',
    appId: '1:575762734530:web:80c233945d577fdf5e0a5b',
    messagingSenderId: '575762734530',
    projectId: 'idfy-1e72a',
    authDomain: 'idfy-1e72a.firebaseapp.com',
    databaseURL: 'https://idfy-1e72a-default-rtdb.firebaseio.com',
    storageBucket: 'idfy-1e72a.firebasestorage.app',
    measurementId: 'G-HV4RS6K6HE',
  );
}
